import TextField from "@mui/material/TextField";
import { useState } from "react";
import Head from "next/head";
import MenuItem from '@mui/material/MenuItem';
import ThankYouModal from "../components/questionnaire/ThankYouModal";
import Image from "next/future/image";
import RatingsButtonsGroup from "../components/questionnaire/RatingsButtonsGroup";
import { trpc } from "../utils/trpc";


const prototypes = [
  {
    value: '1',
    label: 'Prototype 1',
    src: '/PrototypeD1.jpg',
  },
  {
    value: '2',
    label: 'Prototype 2',
    src: '/prototypeS1.png',
  },
  {
    value: '3',
    label: 'Prototype 3',
    src: '/graphS2.png',
  },
  {
    value: '4',
    label: 'Prototype 4',
    src: '/PrototypeS3.png',
  },
  {
    value: '5',
    label: 'Prototype 5',
    src: '/PrototypeD2.png',
  },
  {
    value: '6',
    label: 'Prototype 6',
    src: '/PrototypeS4.png',
  },
  {
    value: '7',
    label: 'Prototype 7',
    src: '/PrototypeS5.png',
  },
  {
    value: '8',
    label: 'Prototype 8',
    src: '/PrototypeS6.png',
  },
];

const OverallFeedback = () => {
  const [feedback, setFeedback] = useState({ favourite: '' });
  const savePttrials = trpc.useraction.savePttrials.useMutation();
  

  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setFeedback({...feedback, [event.target.name]: event.target.value});
  };

  const handleSubmit = async () => {
    const pttrials = (window.localStorage.getItem("pttrials"));
    const username = (window.localStorage.getItem("user"));
    const feedbackData = JSON.stringify(feedback);
    if (pttrials !== null && username !== null ) {
        await savePttrials.mutateAsync({ pttrials, username, feedbackData })  
      } 
       
  }

  return (
    <>
      <Head>
        <title>feedback form</title>
        <meta name="feedback form" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="my-2 flex justify-center mx-auto">

        <div className="my-12 flex flex-col">
        
        <div className="flex justify-center mb-5 ">
           <h2 className="text-3xl font-bold">Thank you for checking out our Prototypes</h2>
        </div>

        <div className="flex justify-center mb-12">
           <p>We really appreciate you taking the time to complete this short Prototype feedback form</p>
        </div>

        <div>
        
        </div>

    <div className="flex justify-center mx-auto flex-col bg-[#eff1f4] p-12 rounded-xl">


          {prototypes.map((option) => ( 
        <div key={option.value} className="mb-12">
            <div className="flex-row" key={option.value}>
              <Image 
                src={option.src}
                alt={option.label}
                width="90"
                height="90"/>
                <h3 className="font-bold">{option.label}</h3>
            </div>
          <RatingsButtonsGroup/>
        </div>
         ))}
        

        <div className="mb-14 mx-auto">
          <TextField
          id="outlined-select-currency"
          select
          label="Select"
          name="favourite"
          value={feedback.favourite}
          onChange={handleChange}
          helperText="Please select your favourite Prototype"
        >
          {prototypes.map((option) => (    
            <MenuItem key={option.value} value={option.value}>
              {option.label} 
              <Image 
                src={option.src}
                alt={option.label}
                width="90"
                height="90"/>
            </MenuItem>
          ))}
        </TextField>
          </div>

          <div className="flex justify-center">
              <ThankYouModal handleSubmit={handleSubmit} />
          </div>

          </div>
        </div>
        
      </main>
    </>
  );
};

export default OverallFeedback;
